# Generated by Django 5.1.4 on 2024-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('short_desc', models.CharField(default='', max_length=300)),
                ('content', models.TextField()),
                ('tumbnail', models.ImageField(upload_to='blogimages')),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
