# Generated by Django 5.1.4 on 2024-12-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
