# Generated by Django 5.1.4 on 2024-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0004_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=22, max_length=500),
            preserve_default=False,
        ),
    ]
